openapi: 3.0.1
info:
  title: Mindfitness
  description: This a Documentation of your API for the project
  license:
    name: MIT OR Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: http://localhost:3000/api

tags:
- name: Auth
  description: Everything about Authentication
- name: Courses
  description: Access to Mindfitness Courses
- name: Chapters
  description: Operations about Chapters
- name: Categories
  description: Operations about Chapters

paths:
  /login:
    post:
      tags:
      - Auth
      summary: Authenticate a user to your Platform
      operationId: login
      requestBody:
        description: User Credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: body
  /signup:
    post:
      tags:
      - Auth
      summary: Registering a User
      operationId: signup
      requestBody:
        description: Email and password to authenticate
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: successful operation
          content: {}
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: body
  /getUser:
    get:
      tags:
      - Auth
      summary: Get the user informations
      operationId: getUser
      responses:
        200:
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
  /Courses:
    get:
      tags:
      - Courses
      summary: Fetch all the user Courses
      operationId: getCourses
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseArray'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
    post:
      tags:
      - Courses
      summary: 'Create a Course '
      description: This endpoint allows user to create a Course
      operationId: createCourse
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  example: Course name
        required: false
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
  /Courses/{Course_id}:
    put:
      tags:
      - Courses
      summary: modify a Course
      description: This endpoint allows user to modify a Course
      operationId: modifyCourse
      parameters:
      - name: Course_id
        in: path
        description: ID of Course to fetch
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  example: Course name
        required: false
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
    delete:
      tags:
      - Courses
      summary: 'Delete a Course '
      description: This endpoint allows user to delete a Course
      parameters:
      - name: Course_id
        in: path
        description: ID of Course to fetch
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
  /Chapters:
    post:
      tags:
      - Chapters
      summary: 'Create an Chapter '
      description: This endpoint allows user to create an Chapter
      operationId: createChapter
      requestBody:
        content:
          application/json:
            schema:
              required:
              - category_id
              - image
              - name
              - note
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                note:
                  type: string
                category_id:
                  type: number
        required: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
  /Chapters/{Chapter_id}:
    put:
      tags:
      - Chapters
      summary: modify an Chapter
      description: This endpoint allows user to modify an Chapter
      operationId: modifyChapter
      parameters:
      - name: Chapter_id
        in: path
        description: ID of Chapter to fetch
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              required:
              - category_id
              - image
              - name
              - note
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                category_id:
                  type: number
                note:
                  type: string
        required: false
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
    delete:
      tags:
      - Chapters
      summary: Delete an Chapter
      description: This endpoint allows user to delete an Chapter
      operationId: DeleteChapter
      parameters:
      - name: Chapter_id
        in: path
        description: ID of Chapter to fetch
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
  /categories:
    get:
      tags:
      - Categories
      summary: Fetch all the user categories
      operationId: getCategories
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: array
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
    post:
      tags:
      - Categories
      summary: Create a Category
      description: This endpoint allows user to create a Category
      operationId: crateCategory
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
        required: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
  /categories/{category_id}:
    put:
      tags:
      - Categories
      summary: modify a Category
      description: This endpoint allows user to modify a Category
      operationId: modifyCategory
      parameters:
      - name: category_id
        in: path
        description: ID of Chapter to category
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
        required: false
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
      x-codegen-request-body-name: body
    delete:
      tags:
      - Categories
      summary: Delete a Category
      description: This endpoint allows user to delete a category
      operationId: deleteCategory
      parameters:
      - name: category_id
        in: path
        description: ID of Category to fetch
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - basicAuth: []
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: username@gmail.com
        password:
          type: string
          example: myPassword123
    LoginResponse:
      type: object
      properties:
        user:
          type: object
          properties: {}
        token:
          type: string
          example: qlkjyzqsd325.!qspuezappz
    User:
      type: object
      properties:
        email:
          type: string
          example: username@gmail.com
        password:
          type: string
          example: MyPassword123
        userName:
          type: string
          example: Username123
    Course:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user_id:
          type: integer
        created_at:
          type: string
        modifyd_at:
          type: string
    CourseArray:
      type: array
    Chapter:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category_id:
          type: integer
        user_id:
          type: integer
        note:
          type: string
        image:
          type: string
        created_at:
          type: string
        modifyd_at:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Category
        user_id:
          type: integer
          example: 1
        created_at:
          type: string
          example: 2020-09-02T14:48:41.919Z
        modifyd_at:
          type: string
          example: 2020-09-02T14:48:41.919Z
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
    ValidationError:
      type: object
      properties:
        status:
          type: string
          example: error
        field:
          type: string
        message:
          type: string
  responses:
    400:
      description: Bad Request
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    401:
      description: Unauthorized
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: Not Found
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
    422:
      description: Validation Error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ValidationError'
    500:
      description: Internal Server Error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
